### ISSUE TITLE
electrolysis support

### ISSUE THREAD

**Issue by cornop** [hijarian/wayback-for-firefox#12]
According to [this](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/?src=api) addon, wayback-for-firefox blocks [electrolysis](https://wiki.mozilla.org/Electrolysis) in Firefox. It would be nice to fix this, so that users of Electrolysis can continue using this addon.

**Comment by Grossdm** [comment]
Yes, please do fix this.  I finally have e10s running, but I think this looks like the best Internet Archive addon on AMO.
