### ISSUE TITLE
Take snapshot now

### ISSUE THREAD

**Issue by cirosantilli** [hijarian/wayback-for-firefox#2]
Another thing I'd love is to be able to take a snapshot whenever I want. This can currently be done under: https://archive.org/web/ on the UI

**Comment by hijarian** [comment]
Do you mean the block under the "save page now", which allows you to explicitly tell their crawler to index some specific page? It's nice idea, but it'll seriously stretch the self-contained concept of "Open page in Wayback Machine" extension, it wasn't in my intentions to make an UI to all features of Wayback Machine in Firefox.

I like the idea, though. This issue just wasn't my personal itch to be scratched, you know. :) When I needed some page to be crawled to be sure I will find it later (or I need to have rock-stable URL to reference in some published work), it's usually not a problem to go to archive.org and use the text input there. :) Not that frustrating that landing on a 404 and starting an adventure of opening a new tab, copypasting the URL, writing the Wayback Machine's URL by memory in address bar, waiting until their site will load, pasting the URL, and finally waiting until the page I was interested in the first place will end loading.

**Comment by cirosantilli** [comment]
Hey, no problem, if you think it's off scope, feel free to close this. Cheers.

**Comment by hijarian** [comment]
:)
