### ISSUE TITLE
Setting to automatically go to the latest save

### ISSUE THREAD

**Issue by tyaremco** [hijarian/wayback-for-firefox#4]
The majority of the time, I just want to open the latest save that archive.org has available.  There should be a option to have the button behave this way.

IMO there's no real point to bring users to the save calendar page.  When you open a save, the timeline is displayed above the saved page anyway.   The save version can be changed just as easily from there.

**Comment by hijarian** [comment]
Amazing idea! I will surely make an update, then, given the presense of #1 and #3. 

Ironically, I am not reading a lot of dead links now than I did before so I just missed this pain point. Thank you for reminding me this.

**Comment by hijarian** [comment]
This is API for finishing this: https://archive.org/help/wayback_api.php
