### ISSUE TITLE
crashes drop-down menus

### ISSUE THREAD

**Issue by davekimble2** [hijarian/wayback-for-firefox#9]
Lubuntu 14.04, Firefox 46.0.1
wayback 2.0.2

It worked the very first time I tried it, but then damaged something such that ALL APPS fail on clicking on things that cause drop down menus to open.

Typing "1" as part of Lubuntu user login  triggers Lubuntu suspend/hibernate/reboot/shutdown menu to open.

utter chaos - uninstalled, but Firefox problems remain.

this page not displaying properly

It is something to do with the Alt key

**Comment by hijarian** [comment]
@davekimble2 I'm sorry, but how can Firefox extension influence the OS outside of the browser in a way you described? Especially my page-local one.

Can you please provide the steps to reproduce your exact problem? "Worked the very first time I tried it" and "this page not displaying properly" are not precise enough. 

I would like to identify exactly what's wrong with your setup.

**Comment by davekimble2** [comment]
It was probably a wire/contact/chip in the keyboard becoming damaged in such a way that the ALT key appeared to be always pressed, even though the key moved properly, and seemed to occur exactly on the first exit from your code.  Eventually I replaced the keyboard.  Your extension was innocent.

**Comment by hijarian** [comment]
OK, I'm glad you resolved your issues. :+1:
